#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# alembic upgrade head
uvicorn main:app --reload --proxy-headers --reload-dir project --host 0.0.0.0 --port ${APP_PORT} --log-level debug
# uvicorn main:app --reload --proxy-headers --forwarded-allow-ips '*' --reload-dir project --host 0.0.0.0 --port ${APP_HTTPS_PORT} --log-level debug
