"""Add S3Credentials, SystemConfig, remove stream_url from User

Revision ID: 477952827354
Revises: 246d09f7967a
Create Date: 2025-04-24 09:29:56.150801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '477952827354'
down_revision = '246d09f7967a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_encode_profile_details_id', table_name='encode_profile_details')
    op.drop_table('encode_profile_details')
    op.drop_index('ix_video_jobs_id', table_name='video_jobs')
    op.drop_table('video_jobs')
    op.drop_index('ix_encode_profiles_id', table_name='encode_profiles')
    op.drop_table('encode_profiles')
    op.drop_index('unique_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('unique_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('callback_key', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('callback_url', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('callback_secret_key', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('stream_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_activated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email_notification_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email_notification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_id', 'users', ['unique_id'], unique=False)
    op.create_table('encode_profiles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.unique_id'], name='encode_profiles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_encode_profiles_id', 'encode_profiles', ['id'], unique=False)
    op.create_table('video_jobs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('video_filename', mysql.VARCHAR(length=220), nullable=False),
    sa.Column('job_by', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('encoding_profile', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('retry_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('started_at', mysql.DATETIME(), nullable=True),
    sa.Column('ended_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('encoding_profileDetails', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['encoding_profile'], ['encode_profiles.id'], name='video_jobs_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_by'], ['users.unique_id'], name='video_jobs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_video_jobs_id', 'video_jobs', ['id'], unique=False)
    op.create_table('encode_profile_details',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('width', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('height', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('video_bitrate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('audio_bitrate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('audio_channel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('audio_frequency', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sc_threshold', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('profile', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('level', mysql.FLOAT(), nullable=True),
    sa.Column('max_bitrate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bufsize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('movflags', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pix_fmt', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('acodec', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('vcodec', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('force_format', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['encode_profiles.id'], name='encode_profile_details_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_encode_profile_details_id', 'encode_profile_details', ['id'], unique=False)
    # ### end Alembic commands ###
