#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A celery_app.celery_app inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A celery_app.celery_app --broker="${CELERY_BROKER_URL}" flower
# celery -A celery_app.celery_app --broker="${CELERY_BROKER_URL}" --broker_api="${CELERY_BROKER_API}" flower
